### ISSUE TITLE
Error displayed: client/app.ts (3, 23): Cannot find module './app.jade'.

### ISSUE THREAD

**Issue by kevde** [pbastowski/meteor-jade-templates#3]
I tried to install your jade templating so I can use it on meteor app ng2 but it seems there is this error displaying. Though yourwork is ok

**Comment by pbastowski** [comment]
Can you provide a link to a repo?

**Comment by kevde** [comment]
https://github.com/kevde/mosikero/tree/angular2.
I am running on Windows 10

**Comment by kevde** [comment]
I have also a question, It seems meteor doesnt reload my changes on the jade file. Is this feature part of your plugin?

**Comment by pbastowski** [comment]
My package works, but first you need to add the `modules` package to your Meteor project. (Look up Modules in Meteor docs)

```
meteor add modules
```

Without `modules` imports won't work properly.

Then, create an `imports/client` folder in the root of your project and put the files that you want to import there. So, that means app.ts and app.jade will go there. Leave index.html where it is now.

Next, add the file `/client/main.ts` with the following contents (you can import other stuff here too, if you wish)

``` js
    import "/imports/client/app"
```

So, you file structure should look like this:

```
/client
    index.html
    main.ts
/imports/client
    app.ts
    app.jade
```

I hope this helps you.

Update:

I just had another look at your app and noticed that you have other folders (lib, server). With meteor 1.3 anything that does not live in an `imports` folder is loaded and executed eagerly. That means without importing, same as with Meteor 1.2 and before.

So, if you want to be in control of what loads when then you'll need to move all imports into the `imports` folder and then they will execute as expected, that is, only when you import them explicitly.

**Comment by mackbrowne** [comment]
Hello @pbastowski, sadly it doesn't look like this is currently working.  I've tried 

`meteor add modules`

I've tried 

`
import template from './questionsList';
`

`
import template from './questionsList.jade';
`

Both get no errors or problems except the entire template does not display in chrome.

When i try 

`
import template from './questionsList.html';
`

I get the error mentioned above.

Is there anything else I should try before making a branch for you to take a look at?  Otherwise, I'll work on setting up the branch tomorrow morning.

**Comment by pbastowski** [comment]
I'll be away the next three days, so, unfortunately I can't help you right now. I can look at your code again on Monday.

**Comment by mackbrowne** [comment]
sounds good, I'll get a branch up by then

**Comment by pbastowski** [comment]
@mackbrowne do you have a branch for me to look at?

**Comment by mackbrowne** [comment]
I can, but first can I clarify whether this will work with angular 1?

**Comment by pbastowski** [comment]
Yes, it will. I use it with ng1 all the time.

**Comment by mackbrowne** [comment]
[here](https://github.com/mackbrowne/meteor-angular-boilerplate/tree/jade-2) is the branch with your plugin installed.  This specific branch i haven't installed modules yet, but it doesn't seem to make any difference.

[here is the file i changed to jade](https://github.com/mackbrowne/meteor-angular-boilerplate/blob/jade-2/imports/ui/components/partiesList/partiesList.jade)

and

[here is the file that references it](https://github.com/mackbrowne/meteor-angular-boilerplate/blob/jade-2/imports/ui/components/partiesList/partiesList.js)

**Comment by pbastowski** [comment]
@mackbrowne 
I have pushed a new version, which should work fine for you with Babel. The issue has to do with how Babel and TypeScript transpile "default" imports, such as

```
import angular from "angular";
```

Babel will give you what you expect, that is `angular` will have a reference to the singleton angular object. However, TypeScript will give you "undefined".

So, I designed my jade-templates module while working with TypeScript and did not realise that there was a difference. I changed my jade-templates compiler so that it returns the compiled string in the way that Babel expects it. 

Please let me know if it works for you.

**Comment by mackbrowne** [comment]
Thanks man!  I'll take a look and get back to you

**Comment by mackbrowne** [comment]
@pbastowski  it works!  thanks!
